name: GCP Deployment

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'

env:
  REGION: us-central1
  PROJECT_ID: car-predictor-484108

jobs:
  gcp: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker Setup
      uses: docker/setup-buildx-action@v2

    - name: GCP Authentication
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials-json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${REGION}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/car-predictor/app:latest ./app

    - name: Push to Artifact Registry
      run: |
        docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/car-predictor/app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy car-predictor \
        --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/car-predictor/app:latest \
        --region ${REGION} \
        --platform managed \
        --allow-unauthenticated